name: Collection integration

on:
  push:
  schedule:
   - cron: 31 6 * * *  # Run weekly

jobs:
  integration-test:
    name: Integration test using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner-python-version:
        - 3.6
        python-version:
        - 3.6
        - 2.7
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        path: ansible_collections/ngine_io/vultr

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ansible and collection dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Build and install collection
      run: |
        ansible-galaxy collection build .
        ansible-galaxy collection install *.gz

    - name: Add config file
      env:
        CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      run: |
        echo "$CONFIG_FILE" > tests/integration/cloud-config-vultr.ini

    - name: Run the tests
      run: >-
        ansible-test
        integration
        --docker
        -v
        --diff
        --color
        --retry-on-error
        --python ${{ matrix.python-version }}
        --continue-on-error
        --coverage
        smoke/vultr/

    - name: Generate coverage report
      run: >-
        ansible-test
        coverage xml
        -v
        --requirements
        --group-by command
        --group-by version
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
